version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kkk_123
      MYSQL_USER: dev
      MYSQL_PASSWORD: kkk_123
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=msyql
      - MYSQL_PORT=3306
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=kkk_123
      - MYSQL_DATABASE=fibonacci
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app