name: Create and Publish Docker Image

on:
  push:
    branches:
      - mainline
env:
  SECRETS: ${{ toJSON(secrets) }}

jobs:
  build-react:
    uses: saroj-dev-ops/docker-fibonacci-app-aws/.github/workflows/test-and-publish-react-template-workflow.yml@mainline
    with:
      image-name: fobonacci_calculator
      tag: v1
      docker_repo_name: fobonacci_calculator
      module_name: client
      registry_username: ${{ SECRETS.DOCKER_USERNAME }}
      registry_password: ${{ SECRETS.DOCKER_PASSWORD }}

  build-nginx:
    uses: saroj-dev-ops/docker-fibonacci-app-aws/.github/workflows/test-and-publish-services-template-workflow.yml@mainline
    with:
      image-name: fobonacci_calculator
      tag: v1
      docker_repo_name: fobonacci_calculator
      module_name: nginx
      registry_username: ${{ SECRETS.DOCKER_USERNAME }}
      registry_password: ${{ SECRETS.DOCKER_PASSWORD }}

  build-server:
    uses: saroj-dev-ops/docker-fibonacci-app-aws/.github/workflows/test-and-publish-services-template-workflow.yml@mainline
    with:
      image-name: fobonacci_calculator
      tag: v1
      docker_repo_name: fobonacci_calculator
      module_name: server
      registry_username: ${{ SECRETS.DOCKER_USERNAME }}
      registry_password: ${{ SECRETS.DOCKER_PASSWORD }}

  build-worker:
    uses: saroj-dev-ops/docker-fibonacci-app-aws/.github/workflows/test-and-publish-services-template-workflow.yml@mainline
    with:
      image-name: fobonacci_calculator
      tag: v1
      docker_repo_name: fobonacci_calculator
      module_name: worker
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
