name: test_and_publish_docker_image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "latest"
      docker_repo_name:
        required: true
        type: string
      module_name:
        required: true
        type: string
    secrets:
      registry_username:
        required: true
        description: User name to login into Docker registry
      registry_password:
        required: true
        description: Password to login into Docker registry

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kumarsaroj18/${{inputs.docker_repo_name}}_${{inputs.module_name}}
          tags: ${{inputs.tag}}
          dockerfile: ${{inputs.module_name}}/Dockerfile
          directory: ${{inputs.module_name}}
          registry: docker.io
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}